### ISSUE TITLE
Script Failing

### ISSUE THREAD

**Issue by outerjpg** [Bugswriter/redyt#5]
After running the script with my desired subreddit, I see the files appearing in .cache/redyt
HOWEVER, after the script ends all of them dissapear and I get this:

FINISHED --2020-12-30 14:36:14--
Total wall clock time: 16s
Downloaded: 101 files, 38M in 7,3s (5,20 MB/s)
sxiv: /home/outer/.cache/redyt/*.png: No such file or directory
sxiv: /home/outer/.cache/redyt/*.jpg: No such file or directory
sxiv: No valid image file given, aborting

**Comment by MikeCodes2586** [comment]
In line 70 it says `sxiv -a "$cachedir/*.png" "$cachedir/*.jpg"`. I changed it to `sxiv -a "$cachedir"/*.png "$cachedir"/*.jpg` and now it works

**Comment by saloniamatteo** [comment]
Please use the following branch: [AlexBocken/redyt](https://github.com/AlexBocken/redyt)
Or simply wait for @Bugswriter to merge #4, as it contains fixes to both `README.md` and `redyt` that @AlexBocken and I made.

**Comment by rodrigo-sys** [comment]
I'm change this line
`sxiv -a "$cachedir/*.png" "$cachedir/*.jpg"`

for this one
`sxiv -a "$cachedir" `

to fix it

(It's the 70th)

**Comment by Etherum1914** [comment]
> I'm change this line
> `sxiv -a "$cachedir/*.png" "$cachedir/*.jpg"`
> 
> for this one
> `sxiv -a "$cachedir" `
> 
> to fix it
> 
> (It's the 70th)

The issue with that is that it'll also display the duplicate images. If the quotation marks in line 70 are removed, the issue will be fixed.
